[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "npm install && npm run build"
  functions = "functions"


[[redirects]]
from = "/*"
to = "/.netlify/functions/index"
status = 200